version: '3'

services:
  nginx:
    build: containers/nginx
    image: nginx
    container_name: nginx
    ports:
      - 443:443
    networks:
      - inception
    restart: unless-stopped
    volumes:
      - /home/tle/data/wordpress:/var/www/html

  mariadb:
    build: containers/mariadb
    image: mariadb
    container_name: mariadb
    networks:
      - inception
    restart: on-failure
    volumes:
      - /home/tle/data/mariadb:/var/lib/mysql
    environment:
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    env_file:
      - .env

  wordpress:
    build: containers/wordpress
    image: wordpress
    container_name: wordpress
    networks:
      - inception
    restart: on-failure
    volumes:
      - /home/tle/data/wordpress:/var/www/html
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - WORDPRESS_ADMIN=${WORDPRESS_ADMIN}
      - WORDPRESS_ADMIN_PASS=${WORDPRESS_ADMIN_PASS}
      - WORDPRESS_USER=${WORDPRESS_USER}
      - WORDPRESS_USER_PASS=${WORDPRESS_USER_PASS}
    env_file:
      - .env
    depends_on:
      - mariadb

networks:
  inception:
    driver: bridge

volumes:
  mariadb:
    driver: local
    driver_opts:
      o: 'bind'
      type: 'none'
      device: '/home/tle/data/mariadb'

  wordpress:
    driver: local
    driver_opts:
      o: 'bind'
      type: 'none'
      device: '/home/tle/data/wordpress'