version: '3'

services:
  nginx:
    build: containers/nginx
    image: nginx
    container_name: nginx
    ports:
      - 443:443
    networks:
      - inception
    volumes:
      - /home/tle/data/wordpress:/var/www/html
    restart: unless-stopped
  
  mariadb:
    build: containers/mariadb
    image: mariadb
    container_name: mariadb
    networks:
      - inception
    volumes:
      - /home/tle/data/mariadb:/var/lib/mysql
    restart: on-failure
    environment:
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    env_file:
      - ".env"
    
    wordpress:
      build: containers/wordpress
      image: wordpress
      container_name: wordpress
      networks:
        - inception
      volumes:
        - /home/tle/data/wordpress:/var/www/html
      restart: on-failure
      environment:
        - DOMAIN_NAME=${DOMAIN_NAME}
        - MARIADB_DATABASE=${MARIADB_DATABASE}
        - MARIADB_USER=${MARIADB_USER}
        - MARIADB_PASSWORD=${MARIADB_PASSWORD}
        - WORDPRESS_ADMIN=${WORDPRESS_ADMIN}
        - WORDPRESS_ADMIN_PASS=${WORDPRESS_ADMIN_PASSWORD}
        - WORDPRESS_USER=${WORDPRESS_USER}
        - WORPRESS_USER_PASS=${WORPRESS_USER_PASS}
      env_file:
        - ".env"
      depends_on:
        - mariadb

networks:
  inception:
    driver: bridge

volumes:
  database:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /Users/tle/Document/Inception
  wordpress:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /Users/tle/Document/Inception